//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_HR_Master.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_HRMasterSoap")]
    public interface WebService_HRMasterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Login(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Unit_type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Unit_type();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Unit_type", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Unit_typeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branch(string branch_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchAsync(string branch_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_AO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster_AO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_AO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_AOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster_Dashboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_DashboardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_Not", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster_Dashboard_Not();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_Not", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_NotAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_Live", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster_Dashboard_Live();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_Live", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_LiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_One", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster_Dashboard_One();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster_Dashboard_One", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_OneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branches", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchesBasesedName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branchesBasesedName(string branch_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchesBasesedName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesBasesedNameAsync(string branch_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_HRMaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_HRMaster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMasterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Qualifn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Qualifn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Qualifn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_QualifnAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branch_lab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branch_lab();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branch_lab", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branch_labAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Checkup_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Checkup_details(string branchid, string start_date, string end_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Checkup_details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Checkup_detailsAsync(string branchid, string start_date, string end_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Temporarypunchingdetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Temporarypunchingdetails(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Temporarypunchingdetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsAsync(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginTempData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoginTempData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginTempData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoginTempDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporarypunchingdetailsWithLOgName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TemporarypunchingdetailsWithLOgName(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporarypunchingdetailsWithLOgName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsWithLOgNameAsync(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchOfUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branchOfUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchOfUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchOfUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_designation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_designationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int createLogin(string username, string password, string type, string designation, string mailid, string role, string branchid, string logusername, string enterduserid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<int> createLoginAsync(string username, string password, string type, string designation, string mailid, string role, string branchid, string logusername, string enterduserid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Employee_Code", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Employee_Code();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Employee_Code", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Employee_CodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_shift();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shift", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddShift(string shift_id, string empcode, string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddShift", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddShiftAsync(string shift_id, string empcode, string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ShiftAndName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_ShiftAndName(string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ShiftAndName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_ShiftAndNameAsync(string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TEmpName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TEmpName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TEmpName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TEmpNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateShift(string shift_id, string updatedShift, string empcode, string ChangeDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateShift", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateShiftAsync(string shift_id, string updatedShift, string empcode, string ChangeDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shift_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_shift_Details(string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shift_Details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_shift_DetailsAsync(string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporarypunchingdetailsWithoutPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TemporarypunchingdetailsWithoutPhoto(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporarypunchingdetailsWithoutPhoto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsWithoutPhotoAsync(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_daysCountOfEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_daysCountOfEmployees(string startDate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_daysCountOfEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_daysCountOfEmployeesAsync(string startDate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_salaryDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_salaryDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_salaryDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_salaryDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_salaryDetailsWithUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_salaryDetailsWithUsername(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_salaryDetailsWithUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_salaryDetailsWithUsernameAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_userDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_userDetails(string Designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_userDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_userDetailsAsync(string Designation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporaryuserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TemporaryuserDetails(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TemporaryuserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporaryuserDetailsAsync(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designationDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_designationDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_designationDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_designationDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSalary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertSalary(string empcode, string MONTHLY_SALARY, string LEAVE_DAYS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSalary", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertSalaryAsync(string empcode, string MONTHLY_SALARY, string LEAVE_DAYS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSalary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateSalary(int id, string USERNAME, string MONTHLY_SALARY, string LEAVE_DAYS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSalary", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateSalaryAsync(int id, string USERNAME, string MONTHLY_SALARY, string LEAVE_DAYS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_dept_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_dept_Details(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_dept_Details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_dept_DetailsAsync(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNorms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertNorms(string BRANCH, string POST, string NORMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNorms", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertNormsAsync(string BRANCH, string POST, string NORMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNorms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateNorms(int id, string NORMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateNorms", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateNormsAsync(int id, string NORMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffNormsDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffNormsDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffNormsDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffNormsDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_user_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_user_Details(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_user_Details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_user_DetailsAsync(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Norms_Count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Norms_Count();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Norms_Count", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Norms_CountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffNormsDetailsWithBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffNormsDetailsWithBranch(string branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffNormsDetailsWithBranch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffNormsDetailsWithBranchAsync(string branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shiftDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_shiftDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shiftDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStaffShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertStaffShift(string Username, string BRANCH, string shift, string updated_by, string updated_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStaffShift", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertStaffShiftAsync(string Username, string BRANCH, string shift, string updated_by, string updated_on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaffShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateStaffShift(string Username, string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaffShift", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateStaffShiftAsync(string Username, string shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffShiftDetails(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsAsync(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetailsForUnitwise", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffShiftDetailsForUnitwise(string branch_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetailsForUnitwise", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsForUnitwiseAsync(string branch_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetailsWithoutBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffShiftDetailsWithoutBranch();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffShiftDetailsWithoutBranch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsWithoutBranchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffPunchingDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_staffPunchingDetails(string branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_staffPunchingDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_staffPunchingDetailsAsync(string branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Post_Details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Post_Details(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Post_Details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Post_DetailsAsync(string branch_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branchName(string branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchNameAsync(string branchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertLeaveApplicaton", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertLeaveApplicaton(string Username, string AppliedDate, string LeaveDate, string Reason, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertLeaveApplicaton", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertLeaveApplicatonAsync(string Username, string AppliedDate, string LeaveDate, string Reason, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_Attendance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_Attendance(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_Attendance", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_AttendanceAsync(string startDate, string enddate, string empcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveUserDetails(string current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsAsync(string current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetailsForCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveUserDetailsForCancel(string current_month, string Emp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetailsForCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsForCancelAsync(string current_month, string Emp_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetailsForuser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveUserDetailsForuser(string SelectData, string current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveUserDetailsForuser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsForuserAsync(string SelectData, string current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLeaveApplicationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateLeaveApplicationStatus(string Username, string ApprovedStatus, string fromDate, string ToDate, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLeaveApplicationStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateLeaveApplicationStatusAsync(string Username, string ApprovedStatus, string fromDate, string ToDate, string Remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveAppliedCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveAppliedCount(string Username, string Current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveAppliedCount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveAppliedCountAsync(string Username, string Current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveSanctionedCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveSanctionedCount(string Username, string Current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeaveSanctionedCount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveSanctionedCountAsync(string Username, string Current_month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLeaveCancelStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateLeaveCancelStatus(string Username, string CancelStatus, string fromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLeaveCancelStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateLeaveCancelStatusAsync(string Username, string CancelStatus, string fromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewStatusOfLeave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewStatusOfLeave(string Username, string From_date, string To_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewStatusOfLeave", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ViewStatusOfLeaveAsync(string Username, string From_date, string To_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchesMicrolab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_branchesMicrolab();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_branchesMicrolab", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesMicrolabAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TempStaffDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffDetailsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffPersonalDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TempStaffPersonalDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffPersonalDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffPersonalDetailsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTempPersonalData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateTempPersonalData(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTempPersonalData", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateTempPersonalDataAsync(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTempPersonalData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertTempPersonalData(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTempPersonalData", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertTempPersonalDataAsync(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffPersonalReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_TempStaffPersonalReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_TempStaffPersonalReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffPersonalReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shiftReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_shiftReport(string branch, string fromDate, string Todate, string staff_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_shiftReport", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftReportAsync(string branch, string fromDate, string Todate, string staff_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_LastShiftarrangedforEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_LastShiftarrangedforEmployee(string BranchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_LastShiftarrangedforEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_LastShiftarrangedforEmployeeAsync(string BranchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_HRMasterSoapChannel : Web_HR_Master.ServiceReference1.WebService_HRMasterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_HRMasterSoapClient : System.ServiceModel.ClientBase<Web_HR_Master.ServiceReference1.WebService_HRMasterSoap>, Web_HR_Master.ServiceReference1.WebService_HRMasterSoap {
        
        public WebService_HRMasterSoapClient() {
        }
        
        public WebService_HRMasterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_HRMasterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_HRMasterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_HRMasterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Login(string u_name, string pswd) {
            return base.Channel.Login(u_name, pswd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoginAsync(string u_name, string pswd) {
            return base.Channel.LoginAsync(u_name, pswd);
        }
        
        public System.Data.DataSet Get_Unit_type() {
            return base.Channel.Get_Unit_type();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Unit_typeAsync() {
            return base.Channel.Get_Unit_typeAsync();
        }
        
        public System.Data.DataSet Get_branch(string branch_type) {
            return base.Channel.Get_branch(branch_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchAsync(string branch_type) {
            return base.Channel.Get_branchAsync(branch_type);
        }
        
        public System.Data.DataSet Get_HRMaster_AO() {
            return base.Channel.Get_HRMaster_AO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_AOAsync() {
            return base.Channel.Get_HRMaster_AOAsync();
        }
        
        public System.Data.DataSet Get_HRMaster_Dashboard() {
            return base.Channel.Get_HRMaster_Dashboard();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_DashboardAsync() {
            return base.Channel.Get_HRMaster_DashboardAsync();
        }
        
        public System.Data.DataSet Get_HRMaster_Dashboard_Not() {
            return base.Channel.Get_HRMaster_Dashboard_Not();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_NotAsync() {
            return base.Channel.Get_HRMaster_Dashboard_NotAsync();
        }
        
        public System.Data.DataSet Get_HRMaster_Dashboard_Live() {
            return base.Channel.Get_HRMaster_Dashboard_Live();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_LiveAsync() {
            return base.Channel.Get_HRMaster_Dashboard_LiveAsync();
        }
        
        public System.Data.DataSet Get_HRMaster_Dashboard_One() {
            return base.Channel.Get_HRMaster_Dashboard_One();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMaster_Dashboard_OneAsync() {
            return base.Channel.Get_HRMaster_Dashboard_OneAsync();
        }
        
        public System.Data.DataSet Get_branches() {
            return base.Channel.Get_branches();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesAsync() {
            return base.Channel.Get_branchesAsync();
        }
        
        public System.Data.DataSet Get_branchesBasesedName(string branch_name) {
            return base.Channel.Get_branchesBasesedName(branch_name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesBasesedNameAsync(string branch_name) {
            return base.Channel.Get_branchesBasesedNameAsync(branch_name);
        }
        
        public System.Data.DataSet Get_HRMaster() {
            return base.Channel.Get_HRMaster();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_HRMasterAsync() {
            return base.Channel.Get_HRMasterAsync();
        }
        
        public System.Data.DataSet Get_Qualifn() {
            return base.Channel.Get_Qualifn();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_QualifnAsync() {
            return base.Channel.Get_QualifnAsync();
        }
        
        public System.Data.DataSet Get_branch_lab() {
            return base.Channel.Get_branch_lab();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branch_labAsync() {
            return base.Channel.Get_branch_labAsync();
        }
        
        public System.Data.DataSet Get_Checkup_details(string branchid, string start_date, string end_date) {
            return base.Channel.Get_Checkup_details(branchid, start_date, end_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Checkup_detailsAsync(string branchid, string start_date, string end_date) {
            return base.Channel.Get_Checkup_detailsAsync(branchid, start_date, end_date);
        }
        
        public System.Data.DataSet Get_Temporarypunchingdetails(string startDate, string enddate, string empcode) {
            return base.Channel.Get_Temporarypunchingdetails(startDate, enddate, empcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsAsync(string startDate, string enddate, string empcode) {
            return base.Channel.Get_TemporarypunchingdetailsAsync(startDate, enddate, empcode);
        }
        
        public System.Data.DataSet LoginTempData() {
            return base.Channel.LoginTempData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoginTempDataAsync() {
            return base.Channel.LoginTempDataAsync();
        }
        
        public System.Data.DataSet Get_TemporarypunchingdetailsWithLOgName(string startDate, string enddate, string empcode) {
            return base.Channel.Get_TemporarypunchingdetailsWithLOgName(startDate, enddate, empcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsWithLOgNameAsync(string startDate, string enddate, string empcode) {
            return base.Channel.Get_TemporarypunchingdetailsWithLOgNameAsync(startDate, enddate, empcode);
        }
        
        public System.Data.DataSet Get_branchOfUsers() {
            return base.Channel.Get_branchOfUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchOfUsersAsync() {
            return base.Channel.Get_branchOfUsersAsync();
        }
        
        public System.Data.DataSet Get_designation() {
            return base.Channel.Get_designation();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_designationAsync() {
            return base.Channel.Get_designationAsync();
        }
        
        public int createLogin(string username, string password, string type, string designation, string mailid, string role, string branchid, string logusername, string enterduserid) {
            return base.Channel.createLogin(username, password, type, designation, mailid, role, branchid, logusername, enterduserid);
        }
        
        public System.Threading.Tasks.Task<int> createLoginAsync(string username, string password, string type, string designation, string mailid, string role, string branchid, string logusername, string enterduserid) {
            return base.Channel.createLoginAsync(username, password, type, designation, mailid, role, branchid, logusername, enterduserid);
        }
        
        public System.Data.DataSet Get_Employee_Code() {
            return base.Channel.Get_Employee_Code();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Employee_CodeAsync() {
            return base.Channel.Get_Employee_CodeAsync();
        }
        
        public System.Data.DataSet Get_shift() {
            return base.Channel.Get_shift();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftAsync() {
            return base.Channel.Get_shiftAsync();
        }
        
        public int AddShift(string shift_id, string empcode, string shift) {
            return base.Channel.AddShift(shift_id, empcode, shift);
        }
        
        public System.Threading.Tasks.Task<int> AddShiftAsync(string shift_id, string empcode, string shift) {
            return base.Channel.AddShiftAsync(shift_id, empcode, shift);
        }
        
        public System.Data.DataSet Get_ShiftAndName(string EmpCode) {
            return base.Channel.Get_ShiftAndName(EmpCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_ShiftAndNameAsync(string EmpCode) {
            return base.Channel.Get_ShiftAndNameAsync(EmpCode);
        }
        
        public System.Data.DataSet Get_TEmpName() {
            return base.Channel.Get_TEmpName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TEmpNameAsync() {
            return base.Channel.Get_TEmpNameAsync();
        }
        
        public int UpdateShift(string shift_id, string updatedShift, string empcode, string ChangeDate) {
            return base.Channel.UpdateShift(shift_id, updatedShift, empcode, ChangeDate);
        }
        
        public System.Threading.Tasks.Task<int> UpdateShiftAsync(string shift_id, string updatedShift, string empcode, string ChangeDate) {
            return base.Channel.UpdateShiftAsync(shift_id, updatedShift, empcode, ChangeDate);
        }
        
        public System.Data.DataSet Get_shift_Details(string shift) {
            return base.Channel.Get_shift_Details(shift);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_shift_DetailsAsync(string shift) {
            return base.Channel.Get_shift_DetailsAsync(shift);
        }
        
        public System.Data.DataSet Get_TemporarypunchingdetailsWithoutPhoto(string startDate, string enddate, string empcode) {
            return base.Channel.Get_TemporarypunchingdetailsWithoutPhoto(startDate, enddate, empcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporarypunchingdetailsWithoutPhotoAsync(string startDate, string enddate, string empcode) {
            return base.Channel.Get_TemporarypunchingdetailsWithoutPhotoAsync(startDate, enddate, empcode);
        }
        
        public System.Data.DataSet Get_daysCountOfEmployees(string startDate, string enddate) {
            return base.Channel.Get_daysCountOfEmployees(startDate, enddate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_daysCountOfEmployeesAsync(string startDate, string enddate) {
            return base.Channel.Get_daysCountOfEmployeesAsync(startDate, enddate);
        }
        
        public System.Data.DataSet Get_salaryDetails() {
            return base.Channel.Get_salaryDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_salaryDetailsAsync() {
            return base.Channel.Get_salaryDetailsAsync();
        }
        
        public System.Data.DataSet Get_salaryDetailsWithUsername(string UserName) {
            return base.Channel.Get_salaryDetailsWithUsername(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_salaryDetailsWithUsernameAsync(string UserName) {
            return base.Channel.Get_salaryDetailsWithUsernameAsync(UserName);
        }
        
        public System.Data.DataSet Get_userDetails(string Designation) {
            return base.Channel.Get_userDetails(Designation);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_userDetailsAsync(string Designation) {
            return base.Channel.Get_userDetailsAsync(Designation);
        }
        
        public System.Data.DataSet Get_TemporaryuserDetails(string branch_id) {
            return base.Channel.Get_TemporaryuserDetails(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TemporaryuserDetailsAsync(string branch_id) {
            return base.Channel.Get_TemporaryuserDetailsAsync(branch_id);
        }
        
        public System.Data.DataSet Get_designationDetails() {
            return base.Channel.Get_designationDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_designationDetailsAsync() {
            return base.Channel.Get_designationDetailsAsync();
        }
        
        public int InsertSalary(string empcode, string MONTHLY_SALARY, string LEAVE_DAYS) {
            return base.Channel.InsertSalary(empcode, MONTHLY_SALARY, LEAVE_DAYS);
        }
        
        public System.Threading.Tasks.Task<int> InsertSalaryAsync(string empcode, string MONTHLY_SALARY, string LEAVE_DAYS) {
            return base.Channel.InsertSalaryAsync(empcode, MONTHLY_SALARY, LEAVE_DAYS);
        }
        
        public int UpdateSalary(int id, string USERNAME, string MONTHLY_SALARY, string LEAVE_DAYS) {
            return base.Channel.UpdateSalary(id, USERNAME, MONTHLY_SALARY, LEAVE_DAYS);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSalaryAsync(int id, string USERNAME, string MONTHLY_SALARY, string LEAVE_DAYS) {
            return base.Channel.UpdateSalaryAsync(id, USERNAME, MONTHLY_SALARY, LEAVE_DAYS);
        }
        
        public System.Data.DataSet Get_dept_Details(string branch_id) {
            return base.Channel.Get_dept_Details(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_dept_DetailsAsync(string branch_id) {
            return base.Channel.Get_dept_DetailsAsync(branch_id);
        }
        
        public int InsertNorms(string BRANCH, string POST, string NORMS) {
            return base.Channel.InsertNorms(BRANCH, POST, NORMS);
        }
        
        public System.Threading.Tasks.Task<int> InsertNormsAsync(string BRANCH, string POST, string NORMS) {
            return base.Channel.InsertNormsAsync(BRANCH, POST, NORMS);
        }
        
        public int UpdateNorms(int id, string NORMS) {
            return base.Channel.UpdateNorms(id, NORMS);
        }
        
        public System.Threading.Tasks.Task<int> UpdateNormsAsync(int id, string NORMS) {
            return base.Channel.UpdateNormsAsync(id, NORMS);
        }
        
        public System.Data.DataSet Get_staffNormsDetails() {
            return base.Channel.Get_staffNormsDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffNormsDetailsAsync() {
            return base.Channel.Get_staffNormsDetailsAsync();
        }
        
        public System.Data.DataSet Get_user_Details(string branch_id) {
            return base.Channel.Get_user_Details(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_user_DetailsAsync(string branch_id) {
            return base.Channel.Get_user_DetailsAsync(branch_id);
        }
        
        public System.Data.DataSet Get_Norms_Count() {
            return base.Channel.Get_Norms_Count();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Norms_CountAsync() {
            return base.Channel.Get_Norms_CountAsync();
        }
        
        public System.Data.DataSet Get_staffNormsDetailsWithBranch(string branch) {
            return base.Channel.Get_staffNormsDetailsWithBranch(branch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffNormsDetailsWithBranchAsync(string branch) {
            return base.Channel.Get_staffNormsDetailsWithBranchAsync(branch);
        }
        
        public System.Data.DataSet Get_shiftDetails() {
            return base.Channel.Get_shiftDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftDetailsAsync() {
            return base.Channel.Get_shiftDetailsAsync();
        }
        
        public int InsertStaffShift(string Username, string BRANCH, string shift, string updated_by, string updated_on) {
            return base.Channel.InsertStaffShift(Username, BRANCH, shift, updated_by, updated_on);
        }
        
        public System.Threading.Tasks.Task<int> InsertStaffShiftAsync(string Username, string BRANCH, string shift, string updated_by, string updated_on) {
            return base.Channel.InsertStaffShiftAsync(Username, BRANCH, shift, updated_by, updated_on);
        }
        
        public int UpdateStaffShift(string Username, string shift) {
            return base.Channel.UpdateStaffShift(Username, shift);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStaffShiftAsync(string Username, string shift) {
            return base.Channel.UpdateStaffShiftAsync(Username, shift);
        }
        
        public System.Data.DataSet Get_staffShiftDetails(string branch_id) {
            return base.Channel.Get_staffShiftDetails(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsAsync(string branch_id) {
            return base.Channel.Get_staffShiftDetailsAsync(branch_id);
        }
        
        public System.Data.DataSet Get_staffShiftDetailsForUnitwise(string branch_name) {
            return base.Channel.Get_staffShiftDetailsForUnitwise(branch_name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsForUnitwiseAsync(string branch_name) {
            return base.Channel.Get_staffShiftDetailsForUnitwiseAsync(branch_name);
        }
        
        public System.Data.DataSet Get_staffShiftDetailsWithoutBranch() {
            return base.Channel.Get_staffShiftDetailsWithoutBranch();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffShiftDetailsWithoutBranchAsync() {
            return base.Channel.Get_staffShiftDetailsWithoutBranchAsync();
        }
        
        public System.Data.DataSet Get_staffPunchingDetails(string branch) {
            return base.Channel.Get_staffPunchingDetails(branch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_staffPunchingDetailsAsync(string branch) {
            return base.Channel.Get_staffPunchingDetailsAsync(branch);
        }
        
        public System.Data.DataSet Get_Post_Details(string branch_id) {
            return base.Channel.Get_Post_Details(branch_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Post_DetailsAsync(string branch_id) {
            return base.Channel.Get_Post_DetailsAsync(branch_id);
        }
        
        public System.Data.DataSet Get_branchName(string branchid) {
            return base.Channel.Get_branchName(branchid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchNameAsync(string branchid) {
            return base.Channel.Get_branchNameAsync(branchid);
        }
        
        public int InsertLeaveApplicaton(string Username, string AppliedDate, string LeaveDate, string Reason, string Type) {
            return base.Channel.InsertLeaveApplicaton(Username, AppliedDate, LeaveDate, Reason, Type);
        }
        
        public System.Threading.Tasks.Task<int> InsertLeaveApplicatonAsync(string Username, string AppliedDate, string LeaveDate, string Reason, string Type) {
            return base.Channel.InsertLeaveApplicatonAsync(Username, AppliedDate, LeaveDate, Reason, Type);
        }
        
        public System.Data.DataSet get_Attendance(string startDate, string enddate, string empcode) {
            return base.Channel.get_Attendance(startDate, enddate, empcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_AttendanceAsync(string startDate, string enddate, string empcode) {
            return base.Channel.get_AttendanceAsync(startDate, enddate, empcode);
        }
        
        public System.Data.DataSet GetLeaveUserDetails(string current_month) {
            return base.Channel.GetLeaveUserDetails(current_month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsAsync(string current_month) {
            return base.Channel.GetLeaveUserDetailsAsync(current_month);
        }
        
        public System.Data.DataSet GetLeaveUserDetailsForCancel(string current_month, string Emp_code) {
            return base.Channel.GetLeaveUserDetailsForCancel(current_month, Emp_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsForCancelAsync(string current_month, string Emp_code) {
            return base.Channel.GetLeaveUserDetailsForCancelAsync(current_month, Emp_code);
        }
        
        public System.Data.DataSet GetLeaveUserDetailsForuser(string SelectData, string current_month) {
            return base.Channel.GetLeaveUserDetailsForuser(SelectData, current_month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveUserDetailsForuserAsync(string SelectData, string current_month) {
            return base.Channel.GetLeaveUserDetailsForuserAsync(SelectData, current_month);
        }
        
        public int UpdateLeaveApplicationStatus(string Username, string ApprovedStatus, string fromDate, string ToDate, string Remarks) {
            return base.Channel.UpdateLeaveApplicationStatus(Username, ApprovedStatus, fromDate, ToDate, Remarks);
        }
        
        public System.Threading.Tasks.Task<int> UpdateLeaveApplicationStatusAsync(string Username, string ApprovedStatus, string fromDate, string ToDate, string Remarks) {
            return base.Channel.UpdateLeaveApplicationStatusAsync(Username, ApprovedStatus, fromDate, ToDate, Remarks);
        }
        
        public System.Data.DataSet GetLeaveAppliedCount(string Username, string Current_month) {
            return base.Channel.GetLeaveAppliedCount(Username, Current_month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveAppliedCountAsync(string Username, string Current_month) {
            return base.Channel.GetLeaveAppliedCountAsync(Username, Current_month);
        }
        
        public System.Data.DataSet GetLeaveSanctionedCount(string Username, string Current_month) {
            return base.Channel.GetLeaveSanctionedCount(Username, Current_month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeaveSanctionedCountAsync(string Username, string Current_month) {
            return base.Channel.GetLeaveSanctionedCountAsync(Username, Current_month);
        }
        
        public int UpdateLeaveCancelStatus(string Username, string CancelStatus, string fromDate, string ToDate) {
            return base.Channel.UpdateLeaveCancelStatus(Username, CancelStatus, fromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<int> UpdateLeaveCancelStatusAsync(string Username, string CancelStatus, string fromDate, string ToDate) {
            return base.Channel.UpdateLeaveCancelStatusAsync(Username, CancelStatus, fromDate, ToDate);
        }
        
        public System.Data.DataSet ViewStatusOfLeave(string Username, string From_date, string To_date) {
            return base.Channel.ViewStatusOfLeave(Username, From_date, To_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ViewStatusOfLeaveAsync(string Username, string From_date, string To_date) {
            return base.Channel.ViewStatusOfLeaveAsync(Username, From_date, To_date);
        }
        
        public System.Data.DataSet Get_branchesMicrolab() {
            return base.Channel.Get_branchesMicrolab();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_branchesMicrolabAsync() {
            return base.Channel.Get_branchesMicrolabAsync();
        }
        
        public System.Data.DataSet Get_TempStaffDetails(string username) {
            return base.Channel.Get_TempStaffDetails(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffDetailsAsync(string username) {
            return base.Channel.Get_TempStaffDetailsAsync(username);
        }
        
        public System.Data.DataSet Get_TempStaffPersonalDetails(string username) {
            return base.Channel.Get_TempStaffPersonalDetails(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffPersonalDetailsAsync(string username) {
            return base.Channel.Get_TempStaffPersonalDetailsAsync(username);
        }
        
        public int UpdateTempPersonalData(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode) {
            return base.Channel.UpdateTempPersonalData(Address, FatherName, Cast, Marital_Status, Married_Details, Gender, Mobile_Number, Residence_phone_number, Qualification, Blood_Group, DateOfJoining, DateOfBirth, EmpCode);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTempPersonalDataAsync(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode) {
            return base.Channel.UpdateTempPersonalDataAsync(Address, FatherName, Cast, Marital_Status, Married_Details, Gender, Mobile_Number, Residence_phone_number, Qualification, Blood_Group, DateOfJoining, DateOfBirth, EmpCode);
        }
        
        public int insertTempPersonalData(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode) {
            return base.Channel.insertTempPersonalData(Address, FatherName, Cast, Marital_Status, Married_Details, Gender, Mobile_Number, Residence_phone_number, Qualification, Blood_Group, DateOfJoining, DateOfBirth, EmpCode);
        }
        
        public System.Threading.Tasks.Task<int> insertTempPersonalDataAsync(string Address, string FatherName, string Cast, string Marital_Status, string Married_Details, string Gender, string Mobile_Number, string Residence_phone_number, string Qualification, string Blood_Group, string DateOfJoining, string DateOfBirth, string EmpCode) {
            return base.Channel.insertTempPersonalDataAsync(Address, FatherName, Cast, Marital_Status, Married_Details, Gender, Mobile_Number, Residence_phone_number, Qualification, Blood_Group, DateOfJoining, DateOfBirth, EmpCode);
        }
        
        public System.Data.DataSet Get_TempStaffPersonalReport() {
            return base.Channel.Get_TempStaffPersonalReport();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TempStaffPersonalReportAsync() {
            return base.Channel.Get_TempStaffPersonalReportAsync();
        }
        
        public System.Data.DataSet Get_shiftReport(string branch, string fromDate, string Todate, string staff_type) {
            return base.Channel.Get_shiftReport(branch, fromDate, Todate, staff_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_shiftReportAsync(string branch, string fromDate, string Todate, string staff_type) {
            return base.Channel.Get_shiftReportAsync(branch, fromDate, Todate, staff_type);
        }
        
        public System.Data.DataSet Get_LastShiftarrangedforEmployee(string BranchId) {
            return base.Channel.Get_LastShiftarrangedforEmployee(BranchId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_LastShiftarrangedforEmployeeAsync(string BranchId) {
            return base.Channel.Get_LastShiftarrangedforEmployeeAsync(BranchId);
        }
    }
}
