//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebServiceTemporaryPunchSoap")]
    public interface WebServiceTemporaryPunchSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPunchDetails(string name, string date, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsAsync(string name, string date, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetailsForDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPunchDetailsForDate(string name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetailsForDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsForDateAsync(string name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchOutDetailsForDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPunchOutDetailsForDate(string name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchOutDetailsForDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPunchOutDetailsForDateAsync(string name, string date);
        
        // CODEGEN: Parameter 'punchinImage' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference2.Add_detailsResponse Add_details(WebApplication1.ServiceReference2.Add_detailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_details", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_detailsResponse> Add_detailsAsync(WebApplication1.ServiceReference2.Add_detailsRequest request);
        
        // CODEGEN: Parameter 'image' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Punchoutdetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse Add_Punchoutdetails(WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Punchoutdetails", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse> Add_PunchoutdetailsAsync(WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest request);
        
        // CODEGEN: Parameter 'PUNCHOUTIMAGE' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPunchout_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference2.InsertPunchout_detailsResponse InsertPunchout_details(WebApplication1.ServiceReference2.InsertPunchout_detailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPunchout_details", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.InsertPunchout_detailsResponse> InsertPunchout_detailsAsync(WebApplication1.ServiceReference2.InsertPunchout_detailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShiftDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetShiftDetails(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShiftDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetShiftDetailsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShiftTimings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetShiftTimings(string shiftid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShiftTimings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetShiftTimingsAsync(string shiftid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCoolOffTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateCoolOffTime(string empcode, string cool_of_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCoolOffTime", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateCoolOffTimeAsync(string empcode, string cool_of_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEarlyGoing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateEarlyGoing(string empcode, string early_Going);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEarlyGoing", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateEarlyGoingAsync(string empcode, string early_Going);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePreviousStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdatePreviousStatus(string empcode, string absent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePreviousStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdatePreviousStatusAsync(string empcode, string absent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPreviousStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertPreviousStatus(string empcode, string absent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPreviousStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertPreviousStatusAsync(string empcode, string absent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetShift(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShift", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetShiftAsync(string Username);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add_details", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Add_detailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] punchinImage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime dateTime;
        
        public Add_detailsRequest() {
        }
        
        public Add_detailsRequest(string username, byte[] punchinImage, string Status, System.DateTime dateTime) {
            this.username = username;
            this.punchinImage = punchinImage;
            this.Status = Status;
            this.dateTime = dateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add_detailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Add_detailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Add_detailsResult;
        
        public Add_detailsResponse() {
        }
        
        public Add_detailsResponse(int Add_detailsResult) {
            this.Add_detailsResult = Add_detailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add_Punchoutdetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Add_PunchoutdetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] image;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime dateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Status;
        
        public Add_PunchoutdetailsRequest() {
        }
        
        public Add_PunchoutdetailsRequest(string username, byte[] image, System.DateTime dateTime, string date, string Status) {
            this.username = username;
            this.image = image;
            this.dateTime = dateTime;
            this.date = date;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add_PunchoutdetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Add_PunchoutdetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Add_PunchoutdetailsResult;
        
        public Add_PunchoutdetailsResponse() {
        }
        
        public Add_PunchoutdetailsResponse(int Add_PunchoutdetailsResult) {
            this.Add_PunchoutdetailsResult = Add_PunchoutdetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPunchout_details", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPunchout_detailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PUNCHOUTIMAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime dateTime;
        
        public InsertPunchout_detailsRequest() {
        }
        
        public InsertPunchout_detailsRequest(string username, byte[] PUNCHOUTIMAGE, string Status, System.DateTime dateTime) {
            this.username = username;
            this.PUNCHOUTIMAGE = PUNCHOUTIMAGE;
            this.Status = Status;
            this.dateTime = dateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPunchout_detailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPunchout_detailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InsertPunchout_detailsResult;
        
        public InsertPunchout_detailsResponse() {
        }
        
        public InsertPunchout_detailsResponse(int InsertPunchout_detailsResult) {
            this.InsertPunchout_detailsResult = InsertPunchout_detailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTemporaryPunchSoapChannel : WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTemporaryPunchSoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap>, WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap {
        
        public WebServiceTemporaryPunchSoapClient() {
        }
        
        public WebServiceTemporaryPunchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTemporaryPunchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTemporaryPunchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTemporaryPunchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet login(string name, string password) {
            return base.Channel.login(name, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(string name, string password) {
            return base.Channel.loginAsync(name, password);
        }
        
        public System.Data.DataSet getPunchDetails(string name, string date, string endDate) {
            return base.Channel.getPunchDetails(name, date, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsAsync(string name, string date, string endDate) {
            return base.Channel.getPunchDetailsAsync(name, date, endDate);
        }
        
        public System.Data.DataSet getPunchDetailsForDate(string name, string date) {
            return base.Channel.getPunchDetailsForDate(name, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsForDateAsync(string name, string date) {
            return base.Channel.getPunchDetailsForDateAsync(name, date);
        }
        
        public System.Data.DataSet getPunchOutDetailsForDate(string name, string date) {
            return base.Channel.getPunchOutDetailsForDate(name, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPunchOutDetailsForDateAsync(string name, string date) {
            return base.Channel.getPunchOutDetailsForDateAsync(name, date);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference2.Add_detailsResponse WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.Add_details(WebApplication1.ServiceReference2.Add_detailsRequest request) {
            return base.Channel.Add_details(request);
        }
        
        public int Add_details(string username, byte[] punchinImage, string Status, System.DateTime dateTime) {
            WebApplication1.ServiceReference2.Add_detailsRequest inValue = new WebApplication1.ServiceReference2.Add_detailsRequest();
            inValue.username = username;
            inValue.punchinImage = punchinImage;
            inValue.Status = Status;
            inValue.dateTime = dateTime;
            WebApplication1.ServiceReference2.Add_detailsResponse retVal = ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).Add_details(inValue);
            return retVal.Add_detailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_detailsResponse> WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.Add_detailsAsync(WebApplication1.ServiceReference2.Add_detailsRequest request) {
            return base.Channel.Add_detailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_detailsResponse> Add_detailsAsync(string username, byte[] punchinImage, string Status, System.DateTime dateTime) {
            WebApplication1.ServiceReference2.Add_detailsRequest inValue = new WebApplication1.ServiceReference2.Add_detailsRequest();
            inValue.username = username;
            inValue.punchinImage = punchinImage;
            inValue.Status = Status;
            inValue.dateTime = dateTime;
            return ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).Add_detailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.Add_Punchoutdetails(WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest request) {
            return base.Channel.Add_Punchoutdetails(request);
        }
        
        public int Add_Punchoutdetails(string username, byte[] image, System.DateTime dateTime, string date, string Status) {
            WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest inValue = new WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest();
            inValue.username = username;
            inValue.image = image;
            inValue.dateTime = dateTime;
            inValue.date = date;
            inValue.Status = Status;
            WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse retVal = ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).Add_Punchoutdetails(inValue);
            return retVal.Add_PunchoutdetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse> WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.Add_PunchoutdetailsAsync(WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest request) {
            return base.Channel.Add_PunchoutdetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference2.Add_PunchoutdetailsResponse> Add_PunchoutdetailsAsync(string username, byte[] image, System.DateTime dateTime, string date, string Status) {
            WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest inValue = new WebApplication1.ServiceReference2.Add_PunchoutdetailsRequest();
            inValue.username = username;
            inValue.image = image;
            inValue.dateTime = dateTime;
            inValue.date = date;
            inValue.Status = Status;
            return ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).Add_PunchoutdetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference2.InsertPunchout_detailsResponse WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.InsertPunchout_details(WebApplication1.ServiceReference2.InsertPunchout_detailsRequest request) {
            return base.Channel.InsertPunchout_details(request);
        }
        
        public int InsertPunchout_details(string username, byte[] PUNCHOUTIMAGE, string Status, System.DateTime dateTime) {
            WebApplication1.ServiceReference2.InsertPunchout_detailsRequest inValue = new WebApplication1.ServiceReference2.InsertPunchout_detailsRequest();
            inValue.username = username;
            inValue.PUNCHOUTIMAGE = PUNCHOUTIMAGE;
            inValue.Status = Status;
            inValue.dateTime = dateTime;
            WebApplication1.ServiceReference2.InsertPunchout_detailsResponse retVal = ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).InsertPunchout_details(inValue);
            return retVal.InsertPunchout_detailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference2.InsertPunchout_detailsResponse> WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap.InsertPunchout_detailsAsync(WebApplication1.ServiceReference2.InsertPunchout_detailsRequest request) {
            return base.Channel.InsertPunchout_detailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference2.InsertPunchout_detailsResponse> InsertPunchout_detailsAsync(string username, byte[] PUNCHOUTIMAGE, string Status, System.DateTime dateTime) {
            WebApplication1.ServiceReference2.InsertPunchout_detailsRequest inValue = new WebApplication1.ServiceReference2.InsertPunchout_detailsRequest();
            inValue.username = username;
            inValue.PUNCHOUTIMAGE = PUNCHOUTIMAGE;
            inValue.Status = Status;
            inValue.dateTime = dateTime;
            return ((WebApplication1.ServiceReference2.WebServiceTemporaryPunchSoap)(this)).InsertPunchout_detailsAsync(inValue);
        }
        
        public System.Data.DataSet GetShiftDetails(string name) {
            return base.Channel.GetShiftDetails(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetShiftDetailsAsync(string name) {
            return base.Channel.GetShiftDetailsAsync(name);
        }
        
        public System.Data.DataSet GetShiftTimings(string shiftid) {
            return base.Channel.GetShiftTimings(shiftid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetShiftTimingsAsync(string shiftid) {
            return base.Channel.GetShiftTimingsAsync(shiftid);
        }
        
        public int UpdateCoolOffTime(string empcode, string cool_of_time) {
            return base.Channel.UpdateCoolOffTime(empcode, cool_of_time);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCoolOffTimeAsync(string empcode, string cool_of_time) {
            return base.Channel.UpdateCoolOffTimeAsync(empcode, cool_of_time);
        }
        
        public int UpdateEarlyGoing(string empcode, string early_Going) {
            return base.Channel.UpdateEarlyGoing(empcode, early_Going);
        }
        
        public System.Threading.Tasks.Task<int> UpdateEarlyGoingAsync(string empcode, string early_Going) {
            return base.Channel.UpdateEarlyGoingAsync(empcode, early_Going);
        }
        
        public int UpdatePreviousStatus(string empcode, string absent) {
            return base.Channel.UpdatePreviousStatus(empcode, absent);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePreviousStatusAsync(string empcode, string absent) {
            return base.Channel.UpdatePreviousStatusAsync(empcode, absent);
        }
        
        public int InsertPreviousStatus(string empcode, string absent) {
            return base.Channel.InsertPreviousStatus(empcode, absent);
        }
        
        public System.Threading.Tasks.Task<int> InsertPreviousStatusAsync(string empcode, string absent) {
            return base.Channel.InsertPreviousStatusAsync(empcode, absent);
        }
        
        public System.Data.DataSet GetShift(string Username) {
            return base.Channel.GetShift(Username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetShiftAsync(string Username) {
            return base.Channel.GetShiftAsync(Username);
        }
    }
}
