//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempory_punching.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch_Type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Branch_Type();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch_Type", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Branch_TypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Branch(string Branch_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Branch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BranchAsync(string Branch_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_pharmacy_patient_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet view_pharmacy_patient_details(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_pharmacy_patient_details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> view_pharmacy_patient_detailsAsync(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_lab_patient_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet view_lab_patient_details(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_lab_patient_details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> view_lab_patient_detailsAsync(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_clinic_patient_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet view_clinic_patient_details(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_clinic_patient_details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> view_clinic_patient_detailsAsync(string Branch_type, string branch_name, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_Registration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int User_Registration(string name, string age, string txt_dob, string address, string Gender, string state, string place, string Qualification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/User_Registration", ReplyAction="*")]
        System.Threading.Tasks.Task<int> User_RegistrationAsync(string name, string age, string txt_dob, string address, string Gender, string state, string place, string Qualification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_details", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet view_details();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_details", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> view_detailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet delete_select(string drname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_select", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> delete_selectAsync(string drname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int update_select(string name, string age, string txt_dob, string address, string gender, string state, string place, string Qualification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_select", ReplyAction="*")]
        System.Threading.Tasks.Task<int> update_selectAsync(string name, string age, string txt_dob, string address, string gender, string state, string place, string Qualification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_details_by_name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet view_details_by_name(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_details_by_name", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> view_details_by_nameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_null_data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet delete_null_data(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_null_data", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> delete_null_dataAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPunchDetails(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunchDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsAsync(string name);
        
        // CODEGEN: Parameter 'image' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/punchOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tempory_punching.ServiceReference1.punchOutResponse punchOut(Tempory_punching.ServiceReference1.punchOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/punchOut", ReplyAction="*")]
        System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.punchOutResponse> punchOutAsync(Tempory_punching.ServiceReference1.punchOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/punchIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int punchIn(string name, string punchin_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/punchIn", ReplyAction="*")]
        System.Threading.Tasks.Task<int> punchInAsync(string name, string punchin_time);
        
        // CODEGEN: Parameter 'image' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePunchInDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tempory_punching.ServiceReference1.updatePunchInDetailsResponse updatePunchInDetails(Tempory_punching.ServiceReference1.updatePunchInDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePunchInDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.updatePunchInDetailsResponse> updatePunchInDetailsAsync(Tempory_punching.ServiceReference1.updatePunchInDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet get_report(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_report", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> get_reportAsync(string name);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="punchOut", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class punchOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string punchOutTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] image;
        
        public punchOutRequest() {
        }
        
        public punchOutRequest(string name, string punchOutTime, byte[] image) {
            this.name = name;
            this.punchOutTime = punchOutTime;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="punchOutResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class punchOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int punchOutResult;
        
        public punchOutResponse() {
        }
        
        public punchOutResponse(int punchOutResult) {
            this.punchOutResult = punchOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePunchInDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updatePunchInDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] image;
        
        public updatePunchInDetailsRequest() {
        }
        
        public updatePunchInDetailsRequest(string username, byte[] image) {
            this.username = username;
            this.image = image;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePunchInDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updatePunchInDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int updatePunchInDetailsResult;
        
        public updatePunchInDetailsResponse() {
        }
        
        public updatePunchInDetailsResponse(int updatePunchInDetailsResult) {
            this.updatePunchInDetailsResult = updatePunchInDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tempory_punching.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tempory_punching.ServiceReference1.WebService1Soap>, Tempory_punching.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_Branch_Type() {
            return base.Channel.Get_Branch_Type();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Branch_TypeAsync() {
            return base.Channel.Get_Branch_TypeAsync();
        }
        
        public System.Data.DataSet Get_Branch(string Branch_type) {
            return base.Channel.Get_Branch(Branch_type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BranchAsync(string Branch_type) {
            return base.Channel.Get_BranchAsync(Branch_type);
        }
        
        public System.Data.DataSet view_pharmacy_patient_details(string Branch_type, string branch_name, string date) {
            return base.Channel.view_pharmacy_patient_details(Branch_type, branch_name, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> view_pharmacy_patient_detailsAsync(string Branch_type, string branch_name, string date) {
            return base.Channel.view_pharmacy_patient_detailsAsync(Branch_type, branch_name, date);
        }
        
        public System.Data.DataSet view_lab_patient_details(string Branch_type, string branch_name, string date) {
            return base.Channel.view_lab_patient_details(Branch_type, branch_name, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> view_lab_patient_detailsAsync(string Branch_type, string branch_name, string date) {
            return base.Channel.view_lab_patient_detailsAsync(Branch_type, branch_name, date);
        }
        
        public System.Data.DataSet view_clinic_patient_details(string Branch_type, string branch_name, string date) {
            return base.Channel.view_clinic_patient_details(Branch_type, branch_name, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> view_clinic_patient_detailsAsync(string Branch_type, string branch_name, string date) {
            return base.Channel.view_clinic_patient_detailsAsync(Branch_type, branch_name, date);
        }
        
        public int User_Registration(string name, string age, string txt_dob, string address, string Gender, string state, string place, string Qualification) {
            return base.Channel.User_Registration(name, age, txt_dob, address, Gender, state, place, Qualification);
        }
        
        public System.Threading.Tasks.Task<int> User_RegistrationAsync(string name, string age, string txt_dob, string address, string Gender, string state, string place, string Qualification) {
            return base.Channel.User_RegistrationAsync(name, age, txt_dob, address, Gender, state, place, Qualification);
        }
        
        public System.Data.DataSet view_details() {
            return base.Channel.view_details();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> view_detailsAsync() {
            return base.Channel.view_detailsAsync();
        }
        
        public System.Data.DataSet delete_select(string drname) {
            return base.Channel.delete_select(drname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> delete_selectAsync(string drname) {
            return base.Channel.delete_selectAsync(drname);
        }
        
        public int update_select(string name, string age, string txt_dob, string address, string gender, string state, string place, string Qualification) {
            return base.Channel.update_select(name, age, txt_dob, address, gender, state, place, Qualification);
        }
        
        public System.Threading.Tasks.Task<int> update_selectAsync(string name, string age, string txt_dob, string address, string gender, string state, string place, string Qualification) {
            return base.Channel.update_selectAsync(name, age, txt_dob, address, gender, state, place, Qualification);
        }
        
        public System.Data.DataSet view_details_by_name(string name) {
            return base.Channel.view_details_by_name(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> view_details_by_nameAsync(string name) {
            return base.Channel.view_details_by_nameAsync(name);
        }
        
        public System.Data.DataSet delete_null_data(string name) {
            return base.Channel.delete_null_data(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> delete_null_dataAsync(string name) {
            return base.Channel.delete_null_dataAsync(name);
        }
        
        public System.Data.DataSet login(string name, string password) {
            return base.Channel.login(name, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> loginAsync(string name, string password) {
            return base.Channel.loginAsync(name, password);
        }
        
        public System.Data.DataSet getPunchDetails(string name) {
            return base.Channel.getPunchDetails(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPunchDetailsAsync(string name) {
            return base.Channel.getPunchDetailsAsync(name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tempory_punching.ServiceReference1.punchOutResponse Tempory_punching.ServiceReference1.WebService1Soap.punchOut(Tempory_punching.ServiceReference1.punchOutRequest request) {
            return base.Channel.punchOut(request);
        }
        
        public int punchOut(string name, string punchOutTime, byte[] image) {
            Tempory_punching.ServiceReference1.punchOutRequest inValue = new Tempory_punching.ServiceReference1.punchOutRequest();
            inValue.name = name;
            inValue.punchOutTime = punchOutTime;
            inValue.image = image;
            Tempory_punching.ServiceReference1.punchOutResponse retVal = ((Tempory_punching.ServiceReference1.WebService1Soap)(this)).punchOut(inValue);
            return retVal.punchOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.punchOutResponse> Tempory_punching.ServiceReference1.WebService1Soap.punchOutAsync(Tempory_punching.ServiceReference1.punchOutRequest request) {
            return base.Channel.punchOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.punchOutResponse> punchOutAsync(string name, string punchOutTime, byte[] image) {
            Tempory_punching.ServiceReference1.punchOutRequest inValue = new Tempory_punching.ServiceReference1.punchOutRequest();
            inValue.name = name;
            inValue.punchOutTime = punchOutTime;
            inValue.image = image;
            return ((Tempory_punching.ServiceReference1.WebService1Soap)(this)).punchOutAsync(inValue);
        }
        
        public int punchIn(string name, string punchin_time) {
            return base.Channel.punchIn(name, punchin_time);
        }
        
        public System.Threading.Tasks.Task<int> punchInAsync(string name, string punchin_time) {
            return base.Channel.punchInAsync(name, punchin_time);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tempory_punching.ServiceReference1.updatePunchInDetailsResponse Tempory_punching.ServiceReference1.WebService1Soap.updatePunchInDetails(Tempory_punching.ServiceReference1.updatePunchInDetailsRequest request) {
            return base.Channel.updatePunchInDetails(request);
        }
        
        public int updatePunchInDetails(string username, byte[] image) {
            Tempory_punching.ServiceReference1.updatePunchInDetailsRequest inValue = new Tempory_punching.ServiceReference1.updatePunchInDetailsRequest();
            inValue.username = username;
            inValue.image = image;
            Tempory_punching.ServiceReference1.updatePunchInDetailsResponse retVal = ((Tempory_punching.ServiceReference1.WebService1Soap)(this)).updatePunchInDetails(inValue);
            return retVal.updatePunchInDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.updatePunchInDetailsResponse> Tempory_punching.ServiceReference1.WebService1Soap.updatePunchInDetailsAsync(Tempory_punching.ServiceReference1.updatePunchInDetailsRequest request) {
            return base.Channel.updatePunchInDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tempory_punching.ServiceReference1.updatePunchInDetailsResponse> updatePunchInDetailsAsync(string username, byte[] image) {
            Tempory_punching.ServiceReference1.updatePunchInDetailsRequest inValue = new Tempory_punching.ServiceReference1.updatePunchInDetailsRequest();
            inValue.username = username;
            inValue.image = image;
            return ((Tempory_punching.ServiceReference1.WebService1Soap)(this)).updatePunchInDetailsAsync(inValue);
        }
        
        public System.Data.DataSet get_report(string name) {
            return base.Channel.get_report(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> get_reportAsync(string name) {
            return base.Channel.get_reportAsync(name);
        }
    }
}
